from .meta import Meta


class ServiceNames(metaclass=Meta):
    class Aws(metaclass=Meta):
        ACM = "acm"
        API_GATEWAY = "apigateway"
        API_GATEWAY_V2 = "apigatewayv2"
        ATHENA = "athena"
        AUTOSCALING = "autoscaling"
        CE = 'ce'
        CLOUD_FORMATION = 'cloudformation'
        CLOUD_FRONT = "cloudfront"
        CLOUD_HSM = "cloudhsm"
        CLOUD_TRAIL = 'cloudtrail'
        CLOUD_WATCH = 'cloudwatch'
        CODE_COMMIT = 'codecommit'
        CONFIG = 'config'
        DYNAMODB = "dynamodb"
        EC2 = "ec2"
        ECR = "ecr"
        ECS = "ecs"
        EFS = "efs"
        EKS = "eks"
        ELASTICACHE = 'elasticache'
        ELB = 'elb'
        ELBV2 = 'elbv2'
        EMR = 'emr'
        ES = 'es'
        FIREHOSE = "firehose"
        GUARDDUTY = "guardduty"
        GLACIER = "glacier"
        GLUE = "glue"
        IAM = 'iam'
        INSPECTOR2 = 'inspector2'
        KINESIS = "kinesis"
        KINESIS_ANALYTICS = "kinesisanalytics"
        KMS = "kms"
        LAMBDA = "lambda"
        LOGS = 'logs'
        MSK = "kafka"
        NEPTUNE = "neptune"
        RDS = "rds"
        ROUTE53 = "route53"
        S3 = "s3"
        SECRETS_MANAGER = "secretsmanager"
        SECURITY_HUB = "securityhub"
        SNS = 'sns'
        SQS = 'sqs'
        STS = 'sts'
        STEP_FUNCTIONS = 'stepfunctions'
        WAF = 'waf'
        WAFV2 = 'wafv2'

    class Kubernetes(metaclass=Meta):
        CLUSTER = "cluster"
        NAMESPACE = "namespace"
        POD = "pod"
        DEPLOYMENT = "deployment"
        STATEFUL_SET = "stateful_set"
        PERSISTENT_VOLUME = "persistent_volume"
        PERSISTENT_VOLUME_CLAIM = "persistent_volume_claim"
        SERVICE = "service"
        INGRESS = "ingress"
        NETWORK_POLICY = "network_policy"
